### PR TITLE
added  changes to sync over all nmap files

### PR DESCRIPTION
**Pull request by archey**

### CODE REVIEW

**Comment by opsdisk** [comment]
Thanks for the PR @archey !  Just a heads up, I won't be able to look at it for a few days.

**Comment by royharoush** [comment]
@archey not sure how, but this commit has exactly the same issue as an issue i previously reported on the original version. dnmaptrace file is not created no server side. 
https://github.com/opsdisk/dnmapR/issues/2

**Comment by archey** [comment]
@royharoush I understand in my testing I did not have this issue let me do some more testing to double check the code. The only things I added was the code to write out grep nmap and xml files from the client to the server from minions code into the server and client side code of this project.

**Comment by archey** [comment]
@royharoush try the commit I just pushed for this. In my testing I was able to verify the nmap file was not being created, I made a few changes and its now sending it over as needed.

**Comment by royharoush** [comment]
@archey it won't get past the first command .. and the file is still not being created :| 
the dnmaptrace should not be sent to the server or to the client. it is a lock file that specifies what was the last command that was successfully executed from the command file. anyway, i'll test it again when opdisk merges. thanks
r

**Comment by archey** [comment]
@royharoush Ill stop messing with it now and let @opsdisk take a look maybe he can fix the trace file if I messed it up. I know the file is being created on the server, but I have not tested it with more then one command.

**Comment by archey** [comment]
@royharoush my latest push has fixes to combine the dnmap minions server and dnmap minions client code with dnmapR. Currently I am using 8 connected clients to it, and jobs are pushed accordingly as a client becomes free. I tested this with multiple jobs, we are gonna start major use of this in prod soon. If I find any more  issues, I will start debugging them and writing fixes for it.

**Comment by royharoush** [comment]
@archey i've tested yesterday, tasks don't seem to finish. are you testing this on 2 different servers ? or at least from 2 different directories ? 
also, the dnmaptrace file is not created and you need to touch $commands+.dnmaptrace to create the file. it's something that was fixed by opdisk in one of his patches ( i think i opened a ticket for it). you sure you pushed the latest version ?

**Comment by opsdisk** [comment]
Hey @archey and @royharoush haven't forgotten about this, just haven't had time to look at it.  I'm actually working on an update to a distributed scanner complete with scheduling and a web front end that I'm pushing to open source.  For the time being, I'll keep this open if you want to chat about the issue, but it won't get any of my limited dev cycles.  I'll let you know when a better distributed scanner is released.

**Comment by royharoush** [comment]
@opsdisk  sounds interesting, is this a fork of minions ?

**Comment by opsdisk** [comment]
It's similar, but has a scheduling feature.

**Comment by opsdisk** [comment]
@royharoush @archey didn't forget about you...just released it this past week through work:  https://github.com/rackerlabs/scantron

Definitely check it out!

**Pull request closed without merging**
